#!/bin/sh

site=build/ipfs.io

# be careful
set -e

# check we have a build dir
if test ! -d build
then
	echo "no build/ directory.  Run make"
	exit 1
fi

# patch with mirror note
cp "$site/index.html" "$site/index2.html"
sed -e '/<!-- ipfs-mirror-note -->/ {
  r mirror.html
  d
}' < "$site/index2.html" >"$site/index.html"

# cname
cp CNAME "$site/CNAME"

echo '==> deploying website to github pages'
git checkout -b deploy
git add -f "$site"
git commit -m "payload"
git checkout master
git filter-branch --subdirectory-filter "$site" -f deploy
git push -f origin deploy:gh-pages
git branch -D deploy
